# Real dataset Experiment

## LastFM

In [7]:
import pandas as pd
# import re
import numpy as np
# from nltk.stem import PorterStemmer
# from nltk.tokenize import word_tokenize
# from nltk.corpus import stopwords

In [8]:
artists_df = pd.read_csv('./raw_ds/hetrec2011-lastfm-2k/artists.dat',sep='\t')
# tags_df = pd.read_csv('./raw_ds/hetrec2011-lastfm-2k/tags.dat',sep='\t', encoding='latin-1')
user_artists_df = pd.read_csv('./raw_ds/hetrec2011-lastfm-2k/user_artists.dat',sep='\t')
# user_taggedartists_df = pd.read_csv('./raw_ds/hetrec2011-lastfm-2k/user_taggedartists.dat',sep='\t')

In [9]:
artists_df[-10:]

id              name                                           url  \
17622  18736         LOSTFREEQ            http://www.last.fm/music/LOSTFREEQ   
17623  18737     Ciccone Youth        http://www.last.fm/music/Ciccone+Youth   
17624  18738          Cubanate             http://www.last.fm/music/Cubanate   
17625  18739        Apollo 440           http://www.last.fm/music/Apollo+440   
17626  18740        Die Krupps           http://www.last.fm/music/Die+Krupps   
17627  18741    Diamanda Galás  http://www.last.fm/music/Diamanda+Gal%C3%A1s   
17628  18742            Aya RL               http://www.last.fm/music/Aya+RL   
17629  18743       Coptic Rain          http://www.last.fm/music/Coptic+Rain   
17630  18744      Oz Alchemist         http://www.last.fm/music/Oz+Alchemist   
17631  18745  Grzegorz Tomczak     http://www.last.fm/music/Grzegorz+Tomczak   

                                              pictureURL  
17622  http://userserve-ak.last.fm/serve/252/24226431...  
17623  http://userserve-ak.last.fm/serve/252/56318105...  
17624  http://userserve-ak.last.fm/serve/252/57473381...  
17625  http://userserve-ak.last.fm/serve/252/6561781.jpg  
17626   http://userserve-ak.last.fm/serve/252/110294.jpg  
17627  http://userserve-ak.last.fm/serve/252/16352971...  
17628   http://userserve-ak.last.fm/serve/252/207445.jpg  
17629   http://userserve-ak.last.fm/serve/252/344868.jpg  
17630  http://userserve-ak.last.fm/serve/252/29297695...  
17631  http://userserve-ak.last.fm/serve/252/59486303...

In [13]:
user_artists_df[:10]

userID  artistID  weight
0       2        51   13883
1       2        52   11690
2       2        53   11351
3       2        54   10300
4       2        55    8983
5       2        56    6152
6       2        57    5955
7       2        58    4616
8       2        59    4337
9       2        60    4147

In [12]:
unique_userID = np.unique(user_artists_df['userID'].values)
unique_artistID = np.unique(artists_df['id'].values)
p_dist = np.zeros((unique_userID.shape[0], unique_artistID.shape[0]))
print(p_dist.shape)
for _, row in user_artists_df.iterrows():
    u_idx = np.where(unique_userID==row['userID'])[0][0]
    a_idx = np.where(unique_artistID==row['artistID'])[0][0]
    p_dist[u_idx, a_idx] = row['weight']
# for i in range(p_dist.shape[0]):
#     p_dist[i] /= p_dist[i].sum()

(1892, 17632)


In [17]:
s = p_dist.sum(axis = 0)
print(s)
print(np.where(s<2))

[ 771. 8012.  775. ...  287.  286.  426.]
(array([ 1164,  2877,  4457,  4458,  5795,  5796,  6134,  7454,  7469,
        7470,  7471,  7472,  7473,  7474,  7475,  7590,  7867,  9246,
        9248,  9249,  9250,  9253,  9255,  9256,  9257,  9258,  9259,
        9260,  9346,  9348,  9350,  9351,  9353,  9355,  9651,  9652,
        9698,  9909, 10904, 10906, 10907, 11256, 11346, 11347, 11348,
       11349, 11350, 11351, 11352, 11964, 11965, 12619, 12620, 12621,
       13013, 13014, 13015, 13169, 13214, 13215, 13216, 13258, 13260,
       13263, 13264, 13266, 13267, 13268, 13269, 13270, 13271, 13272,
       13274, 13275, 13712, 13713, 13769, 13772, 13773, 13774, 13775,
       13776, 13777, 13778, 13883, 13885, 14551, 14965, 15143, 15144,
       15145, 15146, 15147, 15148, 15149, 15151, 15152, 15153, 15154,
       15155, 15588, 15932, 16151, 16235, 16236, 16237, 16238, 16239,
       16240, 16241, 16242, 16243, 16333, 16334, 16335, 16336, 16337,
       16338, 16339, 16340, 16343, 16344, 16345

In [48]:
from collections import Counter
c = Counter(np.argmax(p_dist, axis=1))
# print(c.most_common())
count_threshold = 13
l = []
for tmp in c.most_common():
    artistID, count = tmp
    if count < count_threshold:
        continue
    l.append(artistID)
print(f"Keeping only {len(l)}/17632 artists that are most favorited by more than {count_threshold}/1892 people.")

Keeping only 3/17632 artists that are most favorited by more than 13/1892 people.


# Delicious

In [26]:
bookmarks_df = pd.read_csv('./raw_ds/hetrec2011-delicious-2k/bookmarks.dat',sep='\t', encoding='latin-1')
user_bookmarks_df = pd.read_csv('./raw_ds/hetrec2011-delicious-2k/user_taggedbookmarks.dat',sep='\t')

In [27]:
bookmarks_df

id                               md5  \
0           1  ab4954b633ddaf5b5bba6e9b71aa6b70   
1           2  2221e9cd106d269dd34682666f576fa3   
2           7  c97c571dadaddbbb493126a0d4d01ba3   
3           8  25bfe8dca0ef263ec9c341b9f16c38b5   
4           9  c97284629e17b8e2861afaacd59918bc   
...       ...                               ...   
69221  107247  5a76f2c82314ed0f8f89edfcc38ba0b8   
69222  107248  91e862687e1955e6696f78c1a2695b3f   
69223  107251  2d8a315a9a30612a7499ba6f5d247999   
69224  107252  a56525a58819bccdb94f5a5bab138a8c   
69225  107253  95ed332ae5fb43861b4d2461739b1297   

                                                   title  \
0      IFLA - The official website of the Internation...   
1                    gcdp-e.pdf (application/pdf Object)   
2                                               EdSelect   
3                       Cool Canada (Collections Canada)   
4                                          Kidsreads.com   
...                                                  ...   
69221  Reader&#039;s Theater Editions (Readers Theatr...   
69222                   The Lexile Framework for Reading   
69223     Reading/Language Arts Sunshine State Standards   
69224      ReadWriteThink: Learning Beyond the Classroom   
69225                  International Reading Association   

                                                     url  \
0                                   http://www.ifla.org/   
1         http://archive.ifla.org/VII/s14/nd1/gcdp-e.pdf   
2                               http://www.edselect.com/   
3      http://www.collectionscanada.gc.ca/cool/index-...   
4                              http://www.kidsreads.com/   
...                                                  ...   
69221               http://www.aaronshep.com/rt/RTE.html   
69222  http://www.lexile.com/DesktopDefault.aspx?view...   
69223       http://etc.usf.edu/flstandards/la/index.html   
69224  http://www.readwritethink.org/beyondtheclassro...   
69225                                http://www.ira.org/   

                           md5Principal                 urlPrincipal  
0       7f431306c428457bc4e12b15634484f                 www.ifla.org  
1      1ef8cfcfe968101fa9b4e301847503d4             archive.ifla.org  
2       792fd7eb20143386d0c4eb193c6124d             www.edselect.com  
3      6fce4f6391516f0732531d9cfacda5b7  www.collectionscanada.gc.ca  
4      5854ce8404857a45373eea01a3d98000            www.kidsreads.com  
...                                 ...                          ...  
69221  178bd039b83bec995b3d9cf6a77ae630            www.aaronshep.com  
69222  f9631d79252c5e94173fd89fe7d50a2e               www.lexile.com  
69223  6f029cc4ea200ae73f8e1e8a2282b145                  etc.usf.edu  
69224  a59dd4579a44c144cccf0c981df68eef       www.readwritethink.org  
69225  3508841d603e569727ba2cc74b6d7d3e                  www.ira.org  

[69226 rows x 6 columns]

In [28]:
user_bookmarks_df

userID  bookmarkID  tagID  day  month  year  hour  minute  second
0            8           1      1    8     11  2010    23      29      22
1            8           2      1    8     11  2010    23      25      59
2            8           7      1    8     11  2010    18      55       1
3            8           7      6    8     11  2010    18      55       1
4            8           7      7    8     11  2010    18      55       1
...        ...         ...    ...  ...    ...   ...   ...     ...     ...
437588  108035       30993    193   25      6  2010    21      48      35
437589  108035       30993    673   25      6  2010    21      48      35
437590  108035       30994    130   22      6  2010    18      21      55
437591  108035       30994    267   22      6  2010    18      21      55
437592  108035       30994   4943   22      6  2010    18      21      55

[437593 rows x 9 columns]

In [32]:
unique_userID = np.unique(user_bookmarks_df['userID'].values)
unique_bookmarkID = np.unique(bookmarks_df['id'].values)
p_dist = np.zeros((unique_userID.shape[0], unique_bookmarkID.shape[0]))
print(p_dist.shape)
for _, row in user_bookmarks_df.iterrows():
    u_idx = np.where(unique_userID==row['userID'])[0][0]
    b_idx = np.where(unique_bookmarkID==row['bookmarkID'])[0][0]
    p_dist[u_idx, b_idx] = 1

(1867, 69226)


In [35]:
from itertools import combinations
np.asarray(list(combinations(np.arange(5), 2))).shape

(10, 2)

## Tags processing
Split compound tag into smaller, single word tags

In [93]:
# raw_tags = tags_df['tagValue'].values.astype(str)
# raw_tagIDs = tags_df['tagID'].values.astype(str)
# print(len(raw_tags))

11946


In [99]:
# ps = PorterStemmer()
# stop_words = set(stopwords.words('english')) 

# def word_processing(w):
#     w = ps.stem(w)
#     if len(w)>0 and w not in stop_words:
#         if w[:2]=='19' or w[:2]=='20':
#             if len(w) == 4:
#                 w = w[2:4]
#         else:
#             w = ''.join(sorted(set(w), key=w.index))
#         return w
#     else:
#         return None

# def tag_to_words(tag):
#     tags = []
#     tag = tag.lower()
#     temp = re.split(" |-|_|^|/|'",tag)
#     if type(temp) == str:
#         w = word_processing(temp)
#         if w is not None:
#             tags.append(w)
#     else:
#         for w in temp:
#             w = word_processing(w)
#             if w is not None:
#                 tags.append(w)
#     return tags

# unique_tag_list = []
# for tag in raw_tags:
#     words = tag_to_words(tag)
#     unique_tag_list += words

# unique_tag_list = list(set(unique_tag_list))
# print(len(unique_tag_list))

7751


In [100]:
# mapping_dict = {}
# for index, row in tags_df.iterrows():
#     tags = tag_to_words(row['tagValue'])
#     mapping_dict[row['tagID']] = [unique_tag_list.index(tag) for tag in tags]
# mapping_dict

In [5]:
a = np.arange(7)
print(a.shape)
print(a[::2])
print(a[1::2])

(7,)
[0 2 4 6]
[1 3 5]
